Repository ayush585/edgex, pull requests merged in 2025-09, with the labels that each got.

#76 Enhance Code of Conduct with badges, emojis, and GIFs
  CODE_OF_CONDUCT.md
Labels: GSSoC 25

#80 Added the global dark mode toggle button
  dist/assets/ResourceVault-BC5FfqzA.js
  dist/assets/index-BsPkDgcG.css
  dist/assets/index-DOHAn1wV.js
  dist/assets/index-DP0vNw5C.js
  dist/assets/index-DkSum1YL.css
  dist/assets/index.es-wnmBZhk7.js
  dist/favicon.png
  dist/index.html
  index.html
  package-lock.json
  src/App.jsx
  src/components/Navbar.jsx
  src/index.css
  src/pages/CareerCrack.jsx
  src/pages/Home.jsx
  src/pages/MoodMirror.jsx
  src/pages/ScholarshipScout.jsx
  src/pages/SmartNotes.jsx
  tailwind.config.js
Labels: GSSoC 25, level 3

#86 Google Sign-In & Sign-Up Integration
  src/App.jsx
  src/components/LoginModal.jsx
  src/firebase.js
Labels: enhancement, GSSoC 25, level 3
